### DISCUSSION TITLE
Автоматизуйте оновлення образів контейнерів у Git

### DISCUSSION THREAD

**Discussion by Andygol** [k3ilona/publisher-slack-bot#8] [Ideas]
Source - https://fluxcd.io/flux/guides/image-update/

Цей посібник розповість про налаштування сканування образів контейнера та розгортання за допомогою Flux.

Ви можете налаштувати Flux для роботи з образами контейнерів для:

- сканування реєстру контейнерів та отримання теґів образів
- вибору найостаннішого теґу використовуючи одне з правил (semver, calver, regex)
- перемикання гілок, виконання комітів та push'ів змін у віддалені Git-репозиторії
- застосовувати зміни в кластері та розгортати образи контейнерів

Для продуктових середовищ ця функція дозволяє автоматично розгортати виправлення застосунків (patch, CVE та виправлення помилок), а також вести облік усіх розгортань в історії Git.

**Послідовність дій CI/CD в продуктовому середовищі**

* DEV: додає виправлення помилки до репо застосунку
* DEV: виконує оновлення версії з виправленнями, напр `v1.0.1`
* CI: виконує збирання та надсилання образу контейнера з теґом до реєстру, напр `registry.domain/org/app:v1.0.1`
* CD: витягує найсвіжіші метадані образу з реєстру з образом застосунку (сканування образів Flux)
* CD: виконує оновлення теґу образу в маніфесті застосунку до `v1.0.1` (узгодження Flux кластер -> Git)
* CD: розгортання `v1.0.1` у продуктовому кластері (узгодження Flux Git -> кластер)

```mermaid
sequenceDiagram
autonumber
    participant D as Developer
    participant R1 as Repository
    participant CI as CI
    participant R2 as Registry
    participant CD as CD
    participant C as Cluster

    loop Розробка
        D->>R1: Виправлення помилки
        D->>R1: теґ `v1.0.1`
    end
    loop Інтеграція
        CI-->+R1: Отримання стану репо
        R1->>-CI: Збирання образу 
        CI->>R2: `registry.domain/org/app:v1.0.1`
    end
    loop Розгортання
        CD--)R2: Сканування нових образів
        CD-->>R1: Оновлення теґу образу в маніфесті застосунку до v1.0.1 (узгодження Flux кластер -> Git)
        R1->>CD: Отримання оновленого маніфесту
        CD->>C: Розгортання v1.0.1 
    end
```

Для тестового (staging) середовища ця функція дозволяє розгортати найостаннішу збірку з гілки без потреби в ручному редагуванні маніфестів застосунку в Git.

**Послідовність дій CI/CD в staging середовищі**

* DEV: додає виправлення помилки до репо застосунку  до гілки `main`
* CI: виконує збирання та надсилання образу контейнера до реєстру з теґом `${GIT_BRANCH}-${GIT_SHA:0:7}-$(date +%s)`
* CD: витягує найсвіжіші метадані образу з реєстру з образом застосунку (сканування образів Flux)
* CD: виконує оновлення теґу образу в маніфесті застосунку на `main-2d3fcbd-1611906956` (узгодження Flux кластер -> Git)
* CD: розгортання `main-2d3fcbd-1611906956` у staging кластері (узгодження Flux Git -> кластер)

```mermaid
sequenceDiagram
autonumber
    participant D as Developer
    participant R1 as Repository
    participant CI as CI
    participant R2 as Registry
    participant CD as CD
    participant C as Cluster

    loop Розробка
        D->>R1: Зміни коду
    end
    loop Інтеграція
        CI-->+R1: Отримання стану репо
        R1->>-CI: Збирання образу `${GIT_BRANCH}-${GIT_SHA:0:7}-$(date +%s)`
        CI->>R2: Образ `main-2d3fcbd-1611906956`
    end
    loop Розгортання
        CD--)R2: Сканування нових образів
        CD-->>R1: Оновлення теґу образу в маніфесті застосунку до `main-2d3fcbd-1611906956`  (узгодження Flux кластер -> Git)
        R1->>CD: Отримання оновленого маніфесту

        CD->>C: Розгортання `main-2d3fcbd-1611906956`
    end
```

## Передумови

Вам знадобиться кластер Kubernetes версії 1.16 або новішої та kubectl версії 1.18.
Для швидкого локального тесту ви можете використовувати [Kubernetes kind](https://kind.sigs.k8s.io/docs/user/quick-start/).
Будь-яка інша установка Kubernetes також працюватиме.

Для того, щоб слідувати за цими настанови, вам знадобиться обліковий запис GitHub і [Токен особистого доступу](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) який має права створювати сховища (перевірте всі дозволи в розділі `repo`).

Виконайте експорт токена та облікового запису:

```sh
export GITHUB_TOKEN=<your-token>
export GITHUB_USER=<your-username>
```

## Встановлення Flux

> **Увімкніть компоненти автоматизації роботи з образами**
>
> Якщо ви виконувало `flux bootstrap` перед цим, вам треба буде додати `--components-extra=image-reflector-controller,image-automation-controller` до ваших інструкцій bootstrap компоненти автоматизації роботи з образами контейнерів, бо вони стандартно не встановлюються. Зверніть також увагу на те, що вам треба вилучити секрет `flux-system` перед повторним запуском `flux bootstrap` для [заміни ключів розгортання](https://fluxcd.io/flux/installation/configuration/deploy-key-rotation/)

Встановлення Flux з компонентами автоматизації роботи з образами контейнерів

```sh
flux bootstrap github \
  --components-extra=image-reflector-controller,image-automation-controller \
  --owner=$GITHUB_USER \
  --repository=flux-image-updates \
  --branch=main \
  --path=clusters/my-cluster \
  --read-write-key \
  --personal
```

Команда bootstrap створює репозиторій, якщо його не існує, і заливає маніфести для компонентів Flux до стандартної гілки за вказаним шляхом. Потім він налаштовує цільовий кластер для синхронізації з вказаним шляхом у сховищі.

> **GitLab та інші платформи Git**
>
> Ви можете встановити репозиторії Flux і bootstrap на GitLab, BitBucket, Azure DevOps та будь-якому іншому постачальнику Git, який підтримує SSH або автентифікацію на основі токенів. Під час використання SSH переконайтеся, що ключ розгортання налаштовано з доступом для запису `--read-write-key`. Будь ласка, перегляньте [посібник із встановлення](https://fluxcd.io/flux/guides/installation.md) для отримання додаткової інформації.

## Розгортання демо-застосунка

Будемо використовувати демо-застосунок [podinfo](https://github.com/stefanprodan/podinfo) для демонстрації функції оновлення образів.

Виконаємо клонування репо:

```sh
git clone https://github.com/$GITHUB_USER/flux-image-updates
cd flux-image-updates
```

Створимо розгортання для [podinfo](https://github.com/stefanprodan/podinfo) в кластері `clusters/my-cluster`:

```sh
cat <<EOF > ./clusters/my-cluster/podinfo-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
EOF
```

Застосуємо та заллємо зміни в гілку `main`:

```sh
git add -A && \
git commit -m "add podinfo deployment" && \
git push origin main
```

Скажемо Flux, щоб він витягнув і застосував зміни, або зачекаймо одну хвилину, поки Flux виявить зміни самостійно:

```sh
flux reconcile kustomization flux-system --with-source
```

Отримаємо інформацію про образ podinfo в нашому кластері:

```sh
$ kubectl get deployment/podinfo -oyaml | grep 'image:'
image: ghcr.io/stefanprodan/podinfo:5.0.0
```

## Налаштування сканування образів

Створимо `ImageRepository`, щоб сказати Flux який реєстр образів сканувати на наявність нових теґів:

```sh
flux create image repository podinfo \
--image=ghcr.io/stefanprodan/podinfo \
--interval=5m \
--export > ./clusters/my-cluster/podinfo-registry.yaml
```

Наведена вище команда згенерує наступний маніфест:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: ghcr.io/stefanprodan/podinfo
  interval: 5m
```

Для приватних образів ви можете створити секрет Kubernetes у тому самому просторі імен, що й `ImageRepository`, за допомогою `kubectl create secret docker-registry`. Потім ви можете налаштувати Flux на використання облікових даних, посилаючись на секрет Kubernetes у `ImageRepository`:

```yaml
kind: ImageRepository
spec:
  secretRef:
    name: regcred
```

>  **Зберігання секретів у Git**
> 
> Зауважте, що якщо ви хочете зберегти секрети для витягування образів в Git, ви можете зашифрувати маніфест за допомогою [Mozilla SOPS](https://fluxcd.io/flux/guides/mozilla-sops/) або [Sealed Secrets](https://fluxcd.io/flux/guides/sealed-secrets/).

Створіть `ImagePolicy`, щоб повідомити Flux, який діапазон semver використовувати при фільтрації теґів: 

```sh
flux create image policy podinfo \
--image-ref=podinfo \
--select-semver=5.0.x \
--export > ./clusters/my-cluster/podinfo-policy.yaml
```

Наведена вище команда згенерує наступний маніфест:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 5.0.x
```

Діапазон semver, який включає стабільні випуски, можна визначити за допомогою `1.0.x` (лише версії виправлень) або `>=1.0.0 <2.0.0` (проміжні версії та версії виправлень). Якщо ви хочете включити передрелізну версію, напр. `1.0.0-rc.1`, ви можете визначити діапазон як: `^1.x-0` або `>1.0.0-rc <2.0.0-rc`.

> **Приклади інших правил**
>
> Для політик, які використовують CalVer, ідентифікатори збірки або сортування за алфавітом, перегляньте [приклади] (#Приклади-ImagePolicy).

Застосуємо та заллємо зміни в гілку `main`:

```sh
git add -A && \
git commit -m "add podinfo image scan" && \
git push origin main
```

Скажемо Flux, щоб він витягнув і застосував зміни:

```sh
flux reconcile kustomization flux-system --with-source
```

Зачекаємо, поки Flux отримає список теґів образів з реєстру контейнерів GitHub:

```sh
$ flux get image repository podinfo
NAME    LAST SCAN                       SUSPENDED       READY   MESSAGE
podinfo 2020-12-13T17:51:48+02:00       False           True    successful scan: found 13 tags
```

З метою налагодження, щоб побачити зразок теґів, просканованих `ImageRepository`, список із десяти останніх теґів, просканованих ресурсом `ImageRepository`, можна побачити в статусі ресурсу:

```sh
$ kubectl -n flux-system describe imagerepositories podinfo
...
Status:
  Canonical Image Name:  ghcr.io/stefanprodan/podinfo
  Last Scan Result:
    Latest Tags:
      latest
      6.3.3
      6.3.2
      6.3.1
      6.3.0
      6.2.3
      6.2.2
      6.2.1
      6.2.0
      6.1.8
    Scan Time:  2020-12-13T17:51:48Z
    Tag Count:  13
  Observed Exclusion List:
    ^.*\.sig$
  Observed Generation:  2
...
```

Знайдіть, який теґ образу відповідає діапазону політики:

```sh
$ flux get image policy podinfo
NAME    LATEST IMAGE                            READY   MESSAGE
podinfo ghcr.io/stefanprodan/podinfo:5.0.3      True    Latest image tag for 'ghcr.io/stefanprodan/podinfo' resolved to 5.0.3
```

## Налаштування оновлення образів

Відредагуйте `podinfo-deployment.yaml` і додайте маркер, щоб повідомити Flux, яку політику використовувати при оновленні образу контейнера:

```yaml
spec:
  containers:
  - name: podinfod
    image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "flux-system:podinfo"}
```

Створіть `ImageUpdateAutomation`, щоб повідомити Flux, до якого сховища Git писати оновлення образу:

```sh
flux create image update flux-system \
--interval=30m \
--git-repo-ref=flux-system \
--git-repo-path="./clusters/my-cluster" \
--checkout-branch=main \
--push-branch=main \
--author-name=fluxcdbot \
--author-email=fluxcdbot@users.noreply.github.com \
--commit-template="{{range .Updated.Images}}{{println .}}{{end}}" \
--export > ./clusters/my-cluster/flux-system-automation.yaml
```

Наведена вище команда згенерує наступний маніфест:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./clusters/my-cluster
    strategy: Setters
```

Застосуємо та заллємо зміни в гілку `main`:

```sh
git add -A && \
git commit -m "add image updates automation" && \
git push origin main
```

Зауважте, що `ImageUpdateAutomation` запускає всі політики, знайдені в його просторі імен, у вказаному інтервалі.

Скажіть Flux, щоб він витягнув і застосував зміни:

```sh
flux reconcile kustomization flux-system --with-source
```

За кілька секунд Flux надішле коміт до вашого репозиторію з останнім теґом образу, який відповідає політиці podinfo:

```sh
$ git pull && cat clusters/my-cluster/podinfo-deployment.yaml | grep "image:"
image: ghcr.io/stefanprodan/podinfo:5.0.3 # {"$imagepolicy": "flux-system:podinfo"}
```

Зачекайте, поки Flux застосує останній коміт до кластера, і переконайтеся, що podinfo було оновлено до `5.0.3`:

```sh
$ watch "kubectl get deployment/podinfo -oyaml | grep 'image:'"
image: ghcr.io/stefanprodan/podinfo:5.0.3
```

Ви можете перевірити стан обʼєктів автоматизації образів за допомогою:

```sh
flux get images all --all-namespaces
```

## Налаштування оновлення образів для власних ресурсів

Окрім власних видів Kubernetes (Deployment, StatefulSet, DaemonSet, CronJob), Flux можна використовувати для виправлення посилань на образи в будь-якому спеціальному ресурсі Kubernetes, що зберігається в Git.

Формат маркера політики образу:

* `{"$imagepolicy": "<policy-namespace>:<policy-name>"}`
* `{"$imagepolicy": "<policy-namespace>:<policy-name>:tag"}`
* `{"$imagepolicy": "<policy-namespace>:<policy-name>:name"}`

Ці маркери розміщуються в цільовому YAML як коментарі. Стратегія «Setter» відноситься до [kyaml setters](https://github.com/fluxcd/flux2/discussions/107#discussioncomment-82746), які Flux може знайти та замінити під час узгодження, коли це буде вказано за допомогою `ImageUpdateAutomation ` як зазначено [вище](#Налаштування-оновлення-образів).

Ось кілька прикладів використання цього маркера в різних ресурсах Kubernetes.

Приклад `HelmRelease`:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
      tag: 5.0.0  # {"$imagepolicy": "flux-system:podinfo:tag"}
```

Приклад Tekton `Task`:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang
  namespace: default
spec:
  steps:
    - name: golang
      image: docker.io/golang:1.15.6 # {"$imagepolicy": "flux-system:golang"}
```

Приклад Flux `Kustomization`:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  images:
    - name: ghcr.io/stefanprodan/podinfo
      newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
      newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
```

Приклад Kustomize config (`kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: ghcr.io/stefanprodan/podinfo
  newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
  newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
```

## Надсилання оновлень до іншої гілки

За допомогою `.spec.git.push.branch` ви можете налаштувати Flux для надсилання оновлень образів до іншої гілки, ніж та, яка використовується для перевірки. Якщо вказаної гілки не існує, Flux створить її за вас.

```yaml
kind: ImageUpdateAutomation
metadata:
  name: flux-system
spec:  
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: flux-image-updates
```

Ви можете використовувати автоматизацію CI, напр. Дії GitHub, наприклад Flux [GitHub Actions Auto PR](https://fluxcd.io/flux/use-cases/gh-actions-auto-pr/) для відкриття запиту на отримання (Pull Request).

Таким чином, ви можете вручну затвердити оновлення образів, перш ніж вони будуть застосовані до ваших кластерів.

## Налаштування підпису комітів

Поле `.spec.git.commit.messageTemplate` – це рядок, який використовується як шаблон повідомлення про коміт.

Шаблон повідомлення – це [текстовий шаблон Go](https://golang.org/pkg/text/template/), який дає змогу вказати діапзон об’єктів та образів, наприклад:

```yaml
kind: ImageUpdateAutomation
metadata:
  name: flux-system
spec:
  git:
    commit:
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
```

## Виконання оновлення образів за допомогою webhooks

Можливо, ви захочете запустити розгортання, щойно новий теґ образу буде надіслано до вашого реєстру контейнерів. Щоб сповістити контролер image-reflector-controller про нові образи, ви можете [налаштувати приймачі вебхуків](https://fluxcd.io/flux/guides/webhook-receivers/).

Спочатку згенеруйте випадковий рядок і створіть секрет за допомогою поля `token`:

```sh
TOKEN=$(head -c 12 /dev/urandom | shasum | cut -d ' ' -f1)
echo $TOKEN

kubectl -n flux-system create secret generic webhook-token \	
--from-literal=token=$TOKEN
```

Визначте приймача для DockerHub:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: podinfo
  namespace: flux-system
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: podinfo
```

Контролер сповіщень генерує унікальну URL-адресу, використовуючи наданий токен та назву одержувача чи простір імен.

Знайдіть URL-адресу за допомогою:

```sh
$ kubectl -n flux-system get receiver/podinfo

NAME      READY   STATUS
podinfo   True    Receiver initialised with URL: /hook/bed6d00b5555b1603e1f59b94d7fdbca58089cb5663633fb83f2815dc626d92b
```

Увійдіть у веб-інтерфейс DockerHub, перейдіть до налаштувань реєстру образів і виберіть Webhooks. Заповніть форму «Webhook URL», створивши адресу за допомогою LB одержувача та згенерованої URL-адреси `http://<LoadBalancerAddress>/<ReceiverURL>`.

> **Інші одержувачі**
>
> Окрім DockerHub, ви можете визначити одержувачів для **Harbor**, **Quay**, **Nexus**, **GCR** та будь-якої іншої системи, яка підтримує веб-хуки, наприклад. GitHub Actions, Jenkins, CircleCI тощо. Щоб отримати докладніші відомості, перегляньте [документацію Receiver CRD](https://fluxcd.io/flux/components/notification/receivers/).

### Призупинення автоматизації

Під час інциденту ви можете зупинити Flux, щоб не надсилати оновлення образів до Git.

Ви можете призупинити автоматизацію образів безпосередньо в кластері:

```sh
flux suspend image update flux-system
```

Або відредагувавши маніфест `ImageUpdateAutomation` у Git:

```yaml
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  suspend: true
```

Після того, як інцидент буде вирішено, ви можете відновити автоматизацію за допомогою:

```sh
flux resume image update flux-system
```

Якщо ви хочете призупинити автоматизацію лише для певного образу, ви можете призупинити/відновити сканування образу:

```sh
flux suspend image repository podinfo
```

### Скасування оновлення образу

Припускаючи, що ви налаштували Flux для оновлення програми до останньої стабільної версії:

```sh
flux create image policy podinfo \
--image-ref=podinfo \
--select-semver=">=5.0.0"
```

Якщо остання версія, напр. `5.0.1` викликає інцидент у продуктовому середовищі, ви можете сказати Flux повернути теґ образу до попередньої версії, наприклад. `5.0.0`:

```sh
flux create image policy podinfo \
--image-ref=podinfo \
--select-semver=5.0.0
```

Або змінивши діапазон semver у Git:

```yaml
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  policy:
    semver:
      range: 5.0.0
```

На основі наведеної вище конфігурації Flux виправить маніфест розгортання podinfo в Git і розгорне `5.0.0` у кластері.

Коли доступна нова версія, напр. `5.0.2`, ви можете оновити політику ще раз і сказати Flux розглядати лише версії, старші за `5.0.1`:

```sh
flux create image policy podinfo \
--image-ref=podinfo \
--select-semver=">5.0.1"
```

## Автентифікація хмарних провайдерів ImageRepository

Для автентифікації реєстрів контейнерів як ресурсів `ImageRepository` у Flux доступні два методи:

* Механізми [автоматизованої автентифікації](https://fluxcd.io/flux/components/image/imagerepositories/#provider) (де контролер сам отримує облікові дані та доступний лише для трьох основних хмарних постачальників) або
* * [`CronJob`](https://fluxcd.io/flux/guides/cron-job-image-auth/), який не покладається на підтримку рідної платформи у Flux (натомість зберігає облікові дані як секрети Kubernetes, які періодично оновлюються).

У Flux реалізовано власні механізми автентифікації для трьох основних хмарних провайдерів, але їх потрібно налаштувати в окремих ресурсах `ImageRepository`. Перегляньте окремі розділи, як це зробити.

## Приклади ImagePolicy

Виберіть останню збірку гілки `main`, позначену як `${GIT_BRANCH}-${GIT_SHA:0:7}-$(date +%s)` (числова):

```yaml
kind: ImagePolicy
spec:
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
```

Більш строгим фільтром буде `^main-[a-fA-F0-9]+-(?P<ts>[1-9][0-9]*)`. Перш ніж застосовувати політики в кластері, ви можете перевірити свої фільтри за допомогою [Go тестера регулярних виразів](https://regoio.herokuapp.com) або [regex101.com](https://regex101.com/).

Вибір останньої стабільної версії (semver):

```yaml
kind: ImagePolicy
spec:
  policy:
    semver:
      range: '>=1.0.0'
```

Вибір останньої стабільної версії патча в діапазоні 1.x (semver):

```yaml
kind: ImagePolicy
spec:
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
```

Вибір останньої стабільної версії  разом з пре-релізом (semver):

```yaml
kind: ImagePolicy
spec:
  policy:
    semver:
      range: '>=1.0.0-0'
```

Вибір останньої стабільної версії  кадидата на реліз (semver):

```yaml
kind: ImagePolicy
spec:
  filterTags:
    pattern: '.*-rc.*'
  policy:
    semver:
      range: '^1.x-0'
```

Вибір останньогостабільного випуску з теґом `RELEASE. <RFC3339-TIMESTAMP>` наприклад [Minio](https://hub.docker.com/r/minio/minio) (алфавітний):

```yaml
kind: ImagePolicy
spec:
  filterTags:
    pattern: '^RELEASE\.(?P<timestamp>.*)Z$'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc
```
