### ISSUE TITLE
Теґ образу у вигляді <tag>-<branch>-<sha1>-<timestamp>

### ISSUE THREAD

**Issue by Andygol** [k3ilona/publisher-slack-bot#36]
Flux не підтримує вибір останнього образу за часом збірки. Отримання часу збірки вимагає конфігурації контейнера для кожного зображення та отримання, яке підлягає суворому обмеженню реєстрів образів (наприклад, DockerHub).

Треба, щоб останній образ мав теґ, який є останнім в алфавітному або числовому порядку. Запропонована методика полягає в тому, щоб помістити мітку часу або серійний номер у кожен теґ образу.

Також зручно швидко відстежувати образи в привʼязці до гілки та внести зміни у  його вихідний код. Включення гілки також означає, що ви можете фільтрувати образи з певної гілки.

Корисним форматом теґів може бути

```sh
<tag>-<branch>-<sha1>-<timestamp>
```

Гілка та теґ зазвичай доступні в CI як змінні середовища.

Ось приклад з документації Flux яким можна скористатись

```yaml
jobs:
  build-push:
    env:
        IMAGE: org/my-app
    runs-on: ubuntu-latest
    steps:

    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

    # These are prerequisites for the docker build step
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and publish container image with tag
      uses: docker/build-push-action@v4
      with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
```

Докладніше <https://fluxcd.io/flux/guides/sortable-image-tags/#example-of-a-build-process-with-timestamp-tagging>

Ваші пропозиції?
